# Specify the parent image from which we build
#FROM python:3.8-slim
FROM python:3.12-rc-slim-buster

# Set the working directory
WORKDIR /app

# Copy source code to image
COPY --from=project . .

# Install required packages
RUN pip3 install --no-cache-dir flask
RUN pip install --no-cache-dir requests

LABEL description="ctrlX UI"

EXPOSE 5000

# Run the application
CMD ["python3", "/app/main.py"]
